// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"boat/rpc/user/internal/logic"
	"boat/rpc/user/internal/svc"
	"boat/rpc/user/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) TestErr(ctx context.Context, in *user.TestRequest) (*user.UserResponse, error) {
	l := logic.NewTestErrLogic(ctx, s.svcCtx)
	return l.TestErr(in)
}
