// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	pet "boat/gateway/internal/handler/pet"
	user "boat/gateway/internal/handler/user"
	"boat/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test/err",
				Handler: user.TestErrHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/profile/:id",
				Handler: pet.ProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/pet"),
	)
}
