// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pet/pet.proto

package pet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pet_GetPet_FullMethodName = "/pet.Pet/GetPet"
)

// PetClient is the client API for Pet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PetClient interface {
	GetPet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*PetResponse, error)
}

type petClient struct {
	cc grpc.ClientConnInterface
}

func NewPetClient(cc grpc.ClientConnInterface) PetClient {
	return &petClient{cc}
}

func (c *petClient) GetPet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*PetResponse, error) {
	out := new(PetResponse)
	err := c.cc.Invoke(ctx, Pet_GetPet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetServer is the server API for Pet service.
// All implementations must embed UnimplementedPetServer
// for forward compatibility
type PetServer interface {
	GetPet(context.Context, *IdRequest) (*PetResponse, error)
	mustEmbedUnimplementedPetServer()
}

// UnimplementedPetServer must be embedded to have forward compatible implementations.
type UnimplementedPetServer struct {
}

func (UnimplementedPetServer) GetPet(context.Context, *IdRequest) (*PetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPet not implemented")
}
func (UnimplementedPetServer) mustEmbedUnimplementedPetServer() {}

// UnsafePetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PetServer will
// result in compilation errors.
type UnsafePetServer interface {
	mustEmbedUnimplementedPetServer()
}

func RegisterPetServer(s grpc.ServiceRegistrar, srv PetServer) {
	s.RegisterService(&Pet_ServiceDesc, srv)
}

func _Pet_GetPet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetServer).GetPet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pet_GetPet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetServer).GetPet(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pet_ServiceDesc is the grpc.ServiceDesc for Pet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pet.Pet",
	HandlerType: (*PetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPet",
			Handler:    _Pet_GetPet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pet/pet.proto",
}
