// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `path:"id"`
}

type UserResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type PetReq struct {
	Id int64 `path:"id"`
}

type PetResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
