// Code generated by goctl. DO NOT EDIT.
// Source: pet.proto

package server

import (
	"context"

	"boat/rpc/pet/internal/logic"
	"boat/rpc/pet/internal/svc"
	"boat/rpc/pet/pb/pet"
)

type PetServer struct {
	svcCtx *svc.ServiceContext
	pet.UnimplementedPetServer
}

func NewPetServer(svcCtx *svc.ServiceContext) *PetServer {
	return &PetServer{
		svcCtx: svcCtx,
	}
}

func (s *PetServer) GetPet(ctx context.Context, in *pet.IdRequest) (*pet.PetResponse, error) {
	l := logic.NewGetPetLogic(ctx, s.svcCtx)
	return l.GetPet(in)
}
